### ISSUE TITLE
Feature request: Add support for `real_ip_header` in nginx

### ISSUE THREAD

**Issue by syphernl** [zabbix/zabbix-docker#1278]
##### SUMMARY

Our Zabbix is behind a reverse proxy (Application Gateway) and has the client IP in `X-Forwarded-For`. 
We'd like to instruct nginx to use that IP as client IP rather than the client IP it currently gets, as this is the IP of the loadbalancer.

Usually `real_ip_header X-Forwarded-For;` can be used for that but it doesn't appear this can be easily added to the zabbix-web-nginx without having to modify the container and adding a file to `/etc/nginx/conf.d`

**Comment by dotneft** [comment]
You can use volume mount and mount /etc/nginx/nginx.conf. Is not it solution?

**Comment by syphernl** [comment]
That's actually the workaround/alternative I was implementing. I have mounted a custom config file in the `/etc/nginx/conf.d` folder which works as expected. 

So I guess it doesn't have to be a feature for the container 😄

**Comment by dotneft** [comment]
it is quite difficult to add all possible features of Nginx / PHP-FPM, so it is better in some cases use just additional volumes.

**Comment by mark99i** [comment]
dockerized applications are usually used in conjunction with other reverse proxies such as traefik. this is not a special case, but a common practice.
I searched on the dockerhub page for apache-mysql and nginx-mysql for instructions on env support for specifying a trusted proxy, but I did not find it.
you have variables in env for the most rare cases (for example, ZBX_DB_CIPHER_LIST or ZBX_GUI_ACCESS_IP_RANGE), it is very strange that this issue is closed.
thus, I cannot configure the container via env so that the access list web has the correct ip addresses.
