### ISSUE TITLE
Problem with date in Alpine image

### ISSUE THREAD

**Issue by Raivon** [zabbix/zabbix-docker#174]
When I run `date` in zabbix-server-mysql:alpine-3.4-latest container I see
`Fri Dec  1 08:26:26 +07>-7 2017`
therefore zabbix server send alerts with a wrong time
But on host system (Ubuntu 16.04.3 LTS) I see
`Fri Dec  1 15:31:05 +07 2017`

I use docker-compose and file docker-compose_v2_alpine_mysql_latest.yaml to start app.

I test ubuntu image and there is no problem with date inside the image.

**Comment by canit00** [comment]
You can resolve this very simply by adding the required timezone in your docker-compose file.

Just because you get the desired time with one base image, dont assume they all are built the same.

Please the this [link](https://stackoverflow.com/questions/39172652/using-docker-compose-to-set-containers-timezones) for details.

We got in the habbit of building all our images with the environment variable whether using Dockerfile or docker-compose.

**Comment by Raivon** [comment]
Did you try this? It's excellent work in Ubuntu, but not in Alpine 3.4!

**Comment by dotneft** [comment]
Try to mount /etc/localtime and /etc/timezone. But anyway the question is not related to Zabbix images :-) It is better to ask Alpine community
