### ISSUE TITLE
Facing issues with Zabbix frontend slowness. 

### ISSUE THREAD

**Issue by jainrohitk** [zabbix/zabbix-docker#449]
Hello there, 
my Zabbix frontend is literally very slow & I am tired of searching this improvement options over internet. 

I am running Zabbix 4.0 using docker. 

Let me know how to mitigate this problem.

**Comment by fpaternot** [comment]
I don't think it's a problem with their image.

We have 3 containers that work great with 1.5Tb database and reply on average 30k requests per minute.

Keep in mind that you might need to check your database and/or scale up your containers.

Also, I've noticed that php-fpm does not use dynamic alocation.  I think that's right. You scale your images and that's fine. That's why containers exist in the first place.

Tuning seems fine in the image as well. Nginx is well configured and it uses php7, know for it speed gain compared to its precedents.
