### ISSUE TITLE
Hello Jhonny,

### ISSUE THREAD

**Issue by JhonnyBeGood** [zabbix/zabbix-docker#581]
Hello Jhonny,

> {"log":" 149:20200427:101652.067 [file:dbconfig.c,line:94] __zbx_mem_realloc(): please increase CacheSize configuration parameter\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067500145Z"}

You need to increase Configuration Cache size, for docker use Docker variable ZBX_CACHESIZE=, currently from the output you have only 1024M and it's not enough. 

Also this options could be reduced to:
> -e ZBX_HISTORYCASHSIZE=64M \
> -e ZBX_TRENDCACHESIZE=64M \
> -e ZBX_HISTORYTEXTCASHSIZE=64M \

> and another question: how could I put a damn on the usr/local/etc/zabbix_server.conf file
inside the container

Path to the configuration file inside docker container is /etc/zabbix/zabbix_server.conf. Use docker variables instead of manual editing of the configuration file. 

Regards,
Edgar

_Originally posted by @kernbug in https://github.com/zabbix/zabbix-docker/issues/580#issuecomment-619883617_

**Comment by JhonnyBeGood** [comment]
anyway, right after the zabbix server starts up, Exited (0) About a minute

**Comment by kernbug** [comment]
Could you attach fresh logs?

**Comment by JhonnyBeGood** [comment]
this is my bash script:


#!/bin/bash
echo
echo "Now we create Zabbix Server"
echo
docker run -it \
-d \
--name zbx-server \
--network zbx-network \
-p 10051:10051 \
-e DB_SERVER_HOST=zbx-pgsql \
-e POSTGRES_PASSWORD=zabbix \
-e POSTGRES_USER=zabbix \
-e ZBX_ENABLE_SNMP_TRAPS=TRUE \
-e ZBX_CASHESIZE=6000G \
-e ZBX_HISTORYCASHSIZE=64M \
-e ZBX_TRENDCACHESIZE=64M \
-e ZBX_HISTORYTEXTCASHSIZE=64M \
-e ZBX_VALUECACHESIZE=256M \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/timezone:/etc/timezone:ro \
-v zbx-usr_alertscripts:/usr/lib/zabbix/alertscripts:ro \
-v zbx-usr-extern-scripts:/usr/lib/zabbix/externalscripts:ro \
-v zbx-export:/var/lib/zabbix/export:rw \
-v zbx-modules:/var/lib/zabbix/modules:ro \
-v zbx-enc:/var/lib/zabbix/enc:ro \
-v zbx-ssh-keys:/var/lib/zabbix/ssh_keys:ro \
-v zbx-mibs:/vat/lib/zabbix/mibs:ro \
-v zbx-snmptraps:/var/lib/zabbix/snmptraps:ro \
-v zbx-ssl_certs:/var/lib/zabbix/ssl/certs:ro \
-v zbx-ssl-ssl_ca:/var/lib/zabbix/ssl/ssl_ca:ro \
-v zbx-ssl-keys:/var/lib/zabbix/ssl/keys:ro \
--volumes-from zbx-snmptraps \
zabbix/zabbix-server-pgsql
echo
echo "Zabbix Server is running"


[2cc019049900754edd0416419302ce38d641ef5ed84bcfd0b27ae438f227a331-json.log](https://github.com/zabbix/zabbix-docker/files/4540120/2cc019049900754edd0416419302ce38d641ef5ed84bcfd0b27ae438f227a331-json.log)

**Comment by JhonnyBeGood** [comment]
I'm trying to run a Zabbix complex on Digital Ocean, and there is no such problem with the server

**Comment by kernbug** [comment]
Hello Jhonny,

1. First of all please read carefully: https://hub.docker.com/r/zabbix/zabbix-server-pgsql, word cache should be written like CACHE and not CASHE. You have syntax mistake in script.
2. 6000G = 5.8 Terabyte, do you have such amount of memory?
3. Bash script with multiple lines should be backslashed, script example from you useless since is not working due to the incorrect docker and bash usage. 

Please be advised that this section of the tracker is for bug reports only. 

You can use our IRC channel or community forum (https://www.zabbix.com/forum) for  Bash/Docker scripting assistance. 

With that said, we are closing this ticket. Thank you for understanding.
