### ISSUE TITLE
**** MySQL server is not available. Waiting 5 seconds...

### ISSUE THREAD

**Issue by su-take** [zabbix/zabbix-docker#773]
Hello,
I install Zabbix Docker on Ubuntu 20.04.1 LTS.
When I run "docker logs zabbix-server-mysql",it show the below log.
Will you show the reason?
```
=======  docker logs zabbix-server-mysql ======
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
** Using MYSQL_ROOT_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: _ip address_
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
```
I ran the command below ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
```
docker run --name mysql-server -t  \\
     -e MYSQL_DATABASE="zabbix"       -e MYSQL_USER="zabbix" \\
     -e MYSQL_PASSWORD="zabbix_pwd"       -e MYSQL_ROOT_PASSWORD="root_pwd" \\
      -d mysql:latest       --character-set-server=utf8 --collation-server=utf8_bin \\
      --default-authentication-plugin=mysql_native_password
```
(I don't find why this command cannot run with  the option "--restart unless-stopped")
```
docker run --name zabbix-java-gateway -t \\
       --restart unless-stopped       -d zabbix/zabbix-java-gateway:latest
```
```
docker run --name zabbix-server-mysql -t \\
      -e DB_SERVER_HOST="_ip address_"       -e MYSQL_DATABASE="zabbix" \\
      -e MYSQL_USER="zabbix"       -e MYSQL_PASSWORD="zabbix_pwd" \\
      -e MYSQL_ROOT_PASSWORD="root_pwd"       -e ZBX_JAVAGATEWAY="zabbix-java-gateway" \\
      --link mysql-server:mysql       --link zabbix-java-gateway:zabbix-java-gateway \\
      -p 10051:10051       --restart unless-stopped       -d zabbix/zabbix-server-mysql:ubuntu-latest
```

**Comment by rockaut** [comment]
Sorry I have to ask: you run all the commands on the same host? Why not just use docker-compose?

You're linking the zabbix server to the Java server and the mysql server but then you're using an IP address as DB_SERVER_HOST. There's something wrong.

**Comment by rockaut** [comment]
docker exec into the containers and try if you can reach the other containers with their names. So for example exec I to zabbix server and ping mysql-server.

**Comment by su-take** [comment]
Thank you for rockaut.

I run all commands on the same host.

I follow the procedure below the URL and set up docker at first time.So I don't use docker-compose.
https://www.zabbix.com/documentation/current/manual/installation/containers
I will try docker-compose sometime.

I cannot reach from the other containers with this messages.
root@ai:/home/xxxi# docker exec -it zabbix-server-mysql bash
bash-5.0$ mysql -h _ip-address_ -u zabbix -p zabbix
Enter password:
ERROR 2002 (HY000): Can't connect to MySQL server on '_ip-address_' (115)

And the result from "mysql-server " of  the same containers is below

root@ai:/home/xxx# docker exec -it mysql-server bash
root@a42b648323c0:/# mysql -h _ip-address_ -u zabbix -p zabbix
Enter password:
ERROR 2003 (HY000): Can't connect to MySQL server on '_ip-address_' (111)
root@a42b648323c0:/# mysql -u zabbix -p zabbix
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.0.22 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit

Regards.

**Comment by rockaut** [comment]
Again why ip-address? Always use the container names, you're have to read into docker basics first here (try katacoda.com or any other good tutorial sites for docker basics!)

That aside some quick starting help: I would guess you run into basic docker network troubles here, not zabbix things. There's an amazing container (https://github.com/nicolaka/netshoot) which has all the needed things in it to test basic networking. Depending on the OS you're running from it might be the OS firewall blocking things or just the docker network not configured correctly.

Pull the netshoot image and start it with --net host which gives you basically host-level networking. exec into it and try to ping google.com or whatever.

Start 2 netshoot containers without --net host but with one --name a1 and one --name b1. then exec into each one and try to ping them with "ping a1" "ping b1" which should work.

If this all is not working a would suggest to reinstall docker and try it again.

**Comment by rockaut** [comment]
Sorry but you need to get the basics first. There are a ton of good docker tutorials out there!
Depending on your installation it might be possible that if you "docker run" your containers you might not connect them together at all. You might have to "docker network create" and start the containers with this network attached. Or you can access one because you "--link" it but not the other way in.

Thats what docker-compose is for - it will create an network for each compose file and you will be able to interact between the containers easily.

```yaml
version: '3.8'

services:
  c1:
    image: nicolaka/netshoot
    command: bash
    tty: true
    hostname: c1
  c2:
    image: nicolaka/netshoot
    command: bash
    tty: true
    hostname: c2
```

Where dirname = name of your folder containing the docker-compose.yml file. Here 2 containers will be created dirname_c1_1 and dirname_c2_1. If you "docker network ls" a dirname_default is shown where both containers are available. Exec into them and try to ping them with c1 and c2.

**Comment by rockaut** [comment]
Again, start simple. Zabbix itself might not be the best product to learn your docker basics ;-)

**Comment by shaposhnikoff** [comment]
@su-take Could you please show output of `docker ps ` command when your containers are up and running ? 
Maybe problem in un-exposed ports? I mean 
`docker run -it -p 3306:3306` and so on?

**Comment by paulopaim** [comment]
Hello! I have the same problem with Fedora 33, using docker-compose. on PopOS I don't have this issue.

**Comment by paulopaim** [comment]
> Hello! I have the same problem with Fedora 33, using docker-compose. on PopOS I don't have this issue.

I'm using the file: docker-compose_v3_alpine_mysql_latest.yaml
I attach the logs here.
[docker-zabbix.txt](https://github.com/zabbix/zabbix-docker/files/5718671/docker-zabbix.txt)

**Comment by dotneft** [comment]
I recommend you play with networks and configure public and private network for containers. You can find examples in our documentation: https://www.zabbix.com/documentation/5.0/manual/installation/containers

**Comment by paulopaim** [comment]
> > Hello! I have the same problem with Fedora 33, using docker-compose. on PopOS I don't have this issue.
> 
> I'm using the file: docker-compose_v3_alpine_mysql_latest.yaml
> I attach the logs here.
> [docker-zabbix.txt](https://github.com/zabbix/zabbix-docker/files/5718671/docker-zabbix.txt)

What I found until now, is somehow, the Zabbix database is empty, with no tables.

**Comment by su-take** [comment]
Thanks for everyone (rackaut,shaposhnikoff,paulopaim,dotneft).

The result of "docker ps" is below
docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED      STATUS      PORTS                      NAMES
beb610f20632   zabbix/zabbix-server-mysql:latest   "/sbin/tini -- /usr/…"   2 days ago   Up 2 days   0.0.0.0:10051->10051/tcp   zabbix-server-mysql
471e5169ba0e   zabbix/zabbix-java-gateway:latest   "docker-entrypoint.s…"   3 days ago   Up 3 days   10052/tcp                  zabbix-java-gateway
a42b648323c0   mysql:latest                        "docker-entrypoint.s…"   3 days ago   Up 2 days   3306/tcp, 33060/tcp        mysql-server

And I will configure network. I will post the result latter.

Regards

**Comment by su-take** [comment]
Hello,

I investigated the network of the docker.
I found the ip address of the docker "mysql-server" below the command.
  docker network inspect bridge

When I set 「-e DB_SERVER_HOST="_the upper ip address_"」,I don't show the messages "**** MySQL server is not available. Waiting 5 seconds..." and log in  the web console of Zabbix.

I will try to connect by zabbix agent.

Thanks everyone.

**Comment by neerajkoli** [comment]
When i run docker-compose on ubuntu using centos-mysql  it runs just fine but when running on centos it fails .

**Comment by neerajkoli** [comment]
sudo docker ps -a
[sudo] password for user: 
CONTAINER ID   IMAGE                                              COMMAND                  CREATED       STATUS                   PORTS                                            NAMES
222606d96c1d   zabbix/zabbix-web-apache-mysql:centos-5.2-latest   "docker-entrypoint.sh"   3 hours ago   Up 3 hours (healthy)     0.0.0.0:8000->8080/tcp, 0.0.0.0:4430->8443/tcp   zabbix-docker_zabbix-web-apache-mysql_1
89db9ae73f49   zabbix/zabbix-agent:centos-5.2-latest              "/sbin/tini -- /usr/…"   3 hours ago   Up 3 hours                                                                zabbix-docker_zabbix-agent_1
940ef3483a25   zabbix/zabbix-server-mysql:centos-5.2-latest       "/sbin/tini -- /usr/…"   3 hours ago   Up 3 hours               0.0.0.0:10051->10051/tcp                         zabbix-docker_zabbix-server_1
40f75a1f8d45   zabbix/zabbix-java-gateway:centos-5.2-latest       "docker-entrypoint.s…"   3 hours ago   Up 3 hours                                                                zabbix-docker_zabbix-java-gateway_1
b6ca1fa47df3   mysql:8.0                                          "docker-entrypoint.s…"   3 hours ago   Up 3 hours                                                                zabbix-docker_mysql-server_1
77ef803fb126   busybox                                            "sh"                     3 hours ago   Exited (0) 3 hours ago                                                    zabbix-docker_db_data_mysql_1
f0bc9526f142   zabbix/zabbix-snmptraps:centos-5.2-latest          "/usr/sbin/snmptrapd…"   3 hours ago   Up 3 hours               0.0.0.0:162->1162/udp                            zabbix-docker_zabbix-snmptraps_1

**Comment by neerajkoli** [comment]
"Id": "13e5d0b1021d16931cf4a8ac26c2457e5f951a35acb9da47982a0c249a7f0556",
        "Created": "2021-01-05T12:23:00.282997738Z",
        "Path": "docker-entrypoint.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1695752,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-01-05T12:23:02.301364522Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 3,
                "Log": [
                    {
                        "Start": "2021-01-05T17:53:12.301611567+05:30",
                        "End": "2021-01-05T17:53:12.576401023+05:30",
                        "ExitCode": 7,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused\n"
                    },
                    {
                        "Start": "2021-01-05T17:53:22.639270999+05:30",
                        "End": "2021-01-05T17:53:22.90471505+05:30",
                        "ExitCode": 7,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused\n"
                    },
                    {
                        "Start": "2021-01-05T17:53:32.938842355+05:30",
                        "End": "2021-01-05T17:53:33.207932758+05:30",
                        "ExitCode": 7,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused\n"
                    },

**Comment by dotneft** [comment]
Could you show logs?

**Comment by neerajkoli** [comment]
Logs only shows MySQL is not available .
================================================
** Deploying Zabbix web-interface (Apache) with MySQL database
** Using MYSQL_USER variable from secret file
** Using MYSQL_PASSWORD variable from secret file
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
=============================================
* Preparing Zabbix agent
** Preparing Zabbix agent configuration file
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "PidFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogType": 'console'...added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFileSize": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "DebugLevel": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "SourceIP": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogRemoteCommands": ''...removed
** Using 'zabbix-server' servers for passive checks
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Server": 'zabbix-server'...updated
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenPort": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenIP": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "StartAgents": ''...removed
** Using 'zabbix-server:10051' servers for active checks
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ServerActive": 'zabbix-server:10051'...updated
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostInterface": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostInterfaceItem": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Hostname": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostnameItem": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadata": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadataItem": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "RefreshActiveChecks": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSend": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSize": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "MaxLinesPerSecond": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Timeout": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Include": '/etc/zabbix/zabbix_agentd.d/'...added first occurrence
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "UnsafeUserParameters": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'...added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSConnect": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSAccept": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCAFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCRLFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertIssuer": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertSubject": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCertFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherAll": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherAll13": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherCert": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherCert13": ''...removed
tarting Zabbix Agent [c2f882f67a49]. Zabbix 5.2.3 (revision ae46273).
Press Ctrl+C to exit.

1695627:20210105:175301.874 Starting Zabbix Agent [c2f882f67a49]. Zabbix 5.2.3 (revision ae46273).
1695627:20210105:175301.874 **** Enabled features ****
1695627:20210105:175301.874 IPv6 support:          YES
1695627:20210105:175301.874 TLS support:           YES
1695627:20210105:175301.874 **************************
1695627:20210105:175301.874 using configuration file: /etc/zabbix/zabbix_agentd.conf
1695627:20210105:175301.875 agent #0 started [main process]
1695789:20210105:175301.875 agent #1 started [collector]
1695790:20210105:175301.875 agent #2 started [listener #1]
1695791:20210105:175301.875 agent #3 started [listener #2]
1695792:20210105:175301.875 agent #4 started [listener #3]
1695793:20210105:175301.875 agent #5 started [active checks #1]
1695793:20210105:175302.920 active check configuration update from [zabbix-server:10051] started to fail (cannot connect to [[zabbix-server]:10051]: [113] No route to host)
(END)
===================================================================

** Preparing Zabbix server
** Using MYSQL_USER variable from secret file
** Using MYSQL_PASSWORD variable from secret file
** Using MYSQL_ROOT_PASSWORD variable from secret file
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds..
=================================================
** Preparing Zabbix Java Gateway
** Preparing Zabbix Java Gateway log configuration file
2021-01-05 12:22:56.586 [main] INFO  com.zabbix.gateway.JavaGateway - Zabbix Java Gateway 5.2.3 (revision ae46273) has started
2021-01-05 12:22:56.591 [main] INFO  com.zabbix.gateway.JavaGateway - listening on 0.0.0.0/0.0.0.0:10052
==================================================================


2021-01-05T12:22:56.361784Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
2021-01-05T12:22:56.363286Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2021-01-05T12:22:56.363295Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8_bin' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2021-01-05T12:22:56.384339Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-01-05T12:22:57.700913Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-01-05T12:22:57.962573Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2021-01-05T12:22:58.691139Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-01-05T12:22:58.691311Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-01-05T12:22:58.800356Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-01-05T12:22:58.812682Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2021-01-05 12:22:56+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
2021-01-05 12:22:56+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-01-05 12:22:56+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
(END)
===========================================
[root@Dockerserver ~]# docker network ls
NETWORK ID     NAME                             DRIVER    SCOPE
157ac893f094   bridge                           bridge    local
69b94053efa4   host                             host      local
fc9f03ae3780   none                             null      local
4a4d57bc64d1   zabbix-docker_default            bridge    local
2ee0b7e8249f   zabbix-docker_zbx_net_backend    bridge    local
16333dc0898b   zabbix-docker_zbx_net_frontend   bridge    local
[root@Dockerserver ~]# docker network inspect 2ee0b7e8249f
[
    {
        "Name": "zabbix-docker_zbx_net_backend",
        "Id": "2ee0b7e8249fb8f902c98cefe3a9e3aa27101c894662ec9a1f8ee0b5a6c5a405",
        "Created": "2021-01-05T17:52:52.831808419+05:30",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.239.0/24"
                }
            ]
        },
        "Internal": true,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "13e5d0b1021d16931cf4a8ac26c2457e5f951a35acb9da47982a0c249a7f0556": {
                "Name": "zabbix-docker_zabbix-web-apache-mysql_1",
                "EndpointID": "5e6178c3c0db4481fa61dd228637650b3ab7ad60cea5bd2c7d59b8134fc11a7d",
                "MacAddress": "02:42:ac:10:ef:07",
                "IPv4Address": "172.16.239.7/24",
                "IPv6Address": ""
            },
            "26da7999f3c08f63b5e79447b69b1752cf405595f7c3b4af9a894472158d642f": {
                "Name": "zabbix-docker_zabbix-java-gateway_1",
                "EndpointID": "88eb97f932c053b46de07fd483e399b0dce70ce85e038cd581172a464f1e75f9",
                "MacAddress": "02:42:ac:10:ef:02",
                "IPv4Address": "172.16.239.2/24",
                "IPv6Address": ""
            },
            "5a9cbea48dc50220f2fe0276b3401c8365eff323a0a81e706a6baa74fcaa643c": {
                "Name": "zabbix-docker_zabbix-server_1",
                "EndpointID": "fda3d960cc12f5bab0060e5295c0aabad400bca5d722cf310441826cbb1297b6",
                "MacAddress": "02:42:ac:10:ef:05",
                "IPv4Address": "172.16.239.5/24",
                "IPv6Address": ""
            },
            "6a12879d017364b08c5a6b97b2a341a8fd31d94d55c6b31363a02bc1baa912e7": {
                "Name": "zabbix-docker_zabbix-snmptraps_1",
                "EndpointID": "ee83e56cd9a1ca8b40122ad1330e9ec084201b923295349b7eb1c98b5f85bf78",
                "MacAddress": "02:42:ac:10:ef:04",
                "IPv4Address": "172.16.239.4/24",
                "IPv6Address": ""
            },
            "c2f882f67a49fe040cd50a63de10d1c2fd5612c4d6f950af07cc17b709e0f82b": {
                "Name": "zabbix-docker_zabbix-agent_1",
                "EndpointID": "be8cdd1866b6a54d7764ac1345ad230e901737a971d4ede75787c842b15917ab",
                "MacAddress": "02:42:ac:10:ef:06",
                "IPv4Address": "172.16.239.6/24",
                "IPv6Address": ""
            },
            "ca8c0c91958f3481eb7b86a02fa50bceda0aa991d0031bff506e0d415271f29f": {
                "Name": "zabbix-docker_mysql-server_1",
                "EndpointID": "2b9da443542b7cb8402188904531fea6f9cd0bba3aed6bec5e8eb2a1a72754f7",
                "MacAddress": "02:42:ac:10:ef:03",
                "IPv4Address": "172.16.239.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.enable_ipv6": "false"
        },
        "Labels": {
            "com.docker.compose.network": "zbx_net_backend",
            "com.docker.compose.project": "zabbix-docker",
            "com.docker.compose.version": "1.27.4"
        }
    }
]
[root@Dockerserver ~]#

**Comment by neerajkoli** [comment]
When i connect mysql from host it connects.
===========================================
[root@Dockerserver ~]# mysql -h172.16.239.3 -uzabbix -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.22 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| zabbix             |
+--------------------+
2 rows in set (0.002 sec)

MySQL [(none)]> use zabbix;
Database changed
MySQL [zabbix]> list tables;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'list tables' at line 1
MySQL [zabbix]> show tables;
Empty set (0.001 sec)

MySQL [zabbix]> 
==============================================

when i connect mysql from backend docker instance  it fails .  though  mysql server pings .

[root@Dockerserver ~]# docker exec -it 13e5 bash
bash-4.4$ ping mysql-server
PING mysql-server (172.16.239.3) 56(84) bytes of data.
64 bytes from zabbix-docker_mysql-server_1.zabbix-docker_zbx_net_backend (172.16.239.3): icmp_seq=1 ttl=64 time=0.063 ms
64 bytes from zabbix-docker_mysql-server_1.zabbix-docker_zbx_net_backend (172.16.239.3): icmp_seq=2 ttl=64 time=0.052 ms
^C
--- mysql-server ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 40ms
rtt min/avg/max/mdev = 0.052/0.057/0.063/0.009 ms
bash-4.4$ mysql -h172.16.239.3 -uzabbix -p
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '172.16.239.3' (113)
bash-4.4$

**Comment by neerajkoli** [comment]
no issues on using  docker-compose centos_mysql_latest file on ubuntu host . it just run just fine.

**Comment by dotneft** [comment]
So what it difference? Just different images? Try to specify "DEBUG_MODE=true" for Zabbix server container and attach logs then.

**Comment by su-take** [comment]
Dear,

I could connect to Zabbix Server on docker by zabbix agent.

In my environment,MySQL ran below the command.
(I changed the position of the option "--restart unless-stopped")

When neerajkoli's question will be solved,I would like to close this issue.

docker run --name mysql-server -t \
      --restart unless-stopped \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      --network=zabbix-net \
      -d mysql:latest \
      --character-set-server=utf8 --collation-server=utf8_bin \
      --default-authentication-plugin=mysql_native_password

Thanks,everyone

Regards

**Comment by dotneft** [comment]
What issue do you have at this moment?

**Comment by su-take** [comment]
I don't have an issue.

neerajkoli posted the related issue.So I keep the open.

But Time passed

I close this issue

Thanks,everyone

Regards
