### ISSUE TITLE
zabbix-agent shows strange mount points

### ISSUE THREAD

**Issue by fansari** [zabbix/zabbix-docker#828]
I have tried to replace the zabbix-agent rpm package by the docker version but there are strange issues:

The weirdest thing is that I don't see my mount points like '/' or '/boot' in Zabbix but stuff line '/etc/hostname', '/etc/hosts' or '/etc/resolv.conf' instead (I use "Template OS Linux by Zabbix Agent" - there is autodiscovery for mount points).

I checked how it looks inside the container and this looks like this:

```
7fe435ded8bd:/var/lib/zabbix# df -h
Filesystem           Size  Used Avail Use% Mounted on
overlay               36G  6.8G   29G  20% /
tmpfs                 64M     0   64M   0% /dev
tmpfs                1.9G     0  1.9G   0% /sys/fs/cgroup
shm                   64M     0   64M   0% /dev/shm
/dev/mapper/cl-root   36G  6.8G   29G  20% /etc/hosts
```

Also the network interface is the interface name of the zabbix-agent container, not the interface name of the host.

The agent should not monitor itself but the host, right?

Tested with zabbix/zabbix-agent:alpine-5.2.4

I have replaced the docker version again with the zabbix-agent2 rpm package.

**Comment by dotneft** [comment]
Feel free to use RPM package, sometimes it is better :-)

**Comment by Glideh** [comment]
Discovered file systems are not mount points and I think docker sees mounted volumes as file systems, that's why we are getting files like `/etc/hostname`, `/etc/hosts`, `/etc/resolv.conf` (the 3 of which I guess are mounted by docker internally), `/etc/localtime`, `/etc/timezone` or whatever volumes has been defined at container startup.
I've seen [there](https://github.com/zabbix/zabbix-docker/issues/177) are [there](https://github.com/zabbix/zabbix-docker/blob/6.0/docker-compose_v3_ubuntu_mysql_latest.yaml#L278) people suggesting to use `network_mode: host`, `pid: host` and/or `privileged: true` but it didn't make much difference for me.

Also related: #801

**Comment by ISnotes** [comment]
+1 
Setting the parameters did not help me:
network_mode: host
pid:host
privileged: true

Still seeing weird mount points. Zabbix, can I get feedback? What are we doing wrong?

**Comment by dotneft** [comment]
Just add these mount points to ignore list in LLD, nothing special.

**Comment by ISnotes** [comment]
> Just add these mount points to ignore list in LLD, nothing special.

But then I won't have any information about how much space is available on the disk
